ar rcs include/gnutls.a \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/tls1-prf.o \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/provable-prime.o \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/dsa-keygen-fips186.o \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/rsa-pad.o \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/ecdsa-compute-k.o \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/dsa-compute-k.o \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/mpn-base256.o \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/rsa-keygen-fips186.o \
/home/pi/gnutls-3.7.3/lib/nettle/int/.libs/dsa-validate.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/pk.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/rnd-fuzzer.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/prf.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/sysrng-linux.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/cipher.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/rnd.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/init.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/mac.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/gost_keywrap.o \
/home/pi/gnutls-3.7.3/lib/nettle/.libs/mpi.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/streebog-meta.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/bignum-le.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/streebog.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/gost28147.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/hmac-streebog.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/cmac-magma.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/gost-wrap.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/gostdsa-mask.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/kuznyechik.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/magma.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/cmac-kuznyechik.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/write-le32.o \
/home/pi/gnutls-3.7.3/lib/nettle/gost/.libs/acpkm.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/sign.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/ciphersuites.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/secparams.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/cert_types.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/publickey.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/protocols.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/ciphers.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/ecc.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/mac.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/groups.o \
/home/pi/gnutls-3.7.3/lib/algorithms/.libs/kx.o \
/home/pi/gnutls-3.7.3/lib/inih/.libs/ini.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-mbtouc-unsafe-aux.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u16-uctomb.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-uctomb.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-cpy.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u16-mbtouc-unsafe-aux.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u16-to-u8.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-to-u32.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u32-to-u8.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-uctomb-aux.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u32-cpy.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-check.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u16-uctomb-aux.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-to-u16.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-mbtoucr.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u8-mbtouc-unsafe.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u32-mbtouc-unsafe.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u16-mbtoucr.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u16-cpy.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u16-mbtouc-unsafe.o \
/home/pi/gnutls-3.7.3/lib/unistring/unistr/.libs/u32-uctomb.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Ps.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_N.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_of.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/pr_join_control.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_name.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_test.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/pr_not_a_character.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_or.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Lm.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Pi.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_byname.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Cn.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Co.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_longname.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_C.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Zl.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_So.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Lo.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Pd.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Mc.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_M.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/pr_default_ignorable_code_point.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Nl.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Sm.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/combiningclass.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Cf.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_none.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_No.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Pf.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_L.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Ll.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_and_not.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Lt.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Pe.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Cc.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Mn.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Cs.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_S.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Zp.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Zs.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Me.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Sk.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_P.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Po.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Sc.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Nd.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_and.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Lu.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Z.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_Pc.o \
/home/pi/gnutls-3.7.3/lib/unistring/unictype/.libs/categ_LC.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/composition.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/nfd.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/u16-normalize.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/nfkd.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/compat-decomposition.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/decompose-internal.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/decomposition-table.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/u32-normalize.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/u8-normalize.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/nfkc.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/canonical-decomposition.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/nfc.o \
/home/pi/gnutls-3.7.3/lib/unistring/uninorm/.libs/decomposition.o \
/home/pi/gnutls-3.7.3/lib/.libs/str-unicode.o \
/home/pi/gnutls-3.7.3/lib/.libs/crypto-backend.o \
/home/pi/gnutls-3.7.3/lib/.libs/alert.o \
/home/pi/gnutls-3.7.3/lib/.libs/compress.o \
/home/pi/gnutls-3.7.3/lib/.libs/cert-cred-rawpk.o \
/home/pi/gnutls-3.7.3/lib/.libs/pkcs11_privkey.o \
/home/pi/gnutls-3.7.3/lib/.libs/gnutls_asn1_tab.o \
/home/pi/gnutls-3.7.3/lib/.libs/range.o \
/home/pi/gnutls-3.7.3/lib/.libs/dh-primes.o \
/home/pi/gnutls-3.7.3/lib/.libs/pkcs11.o \
/home/pi/gnutls-3.7.3/lib/.libs/pin.o \
/home/pi/gnutls-3.7.3/lib/.libs/session.o \
/home/pi/gnutls-3.7.3/lib/.libs/hash_int.o \
/home/pi/gnutls-3.7.3/lib/.libs/pkcs11_secret.o \
/home/pi/gnutls-3.7.3/lib/.libs/session_pack.o \
/home/pi/gnutls-3.7.3/lib/.libs/libgnutlsxx_la-gnutlsxx.o \
/home/pi/gnutls-3.7.3/lib/.libs/pcert.o \
/home/pi/gnutls-3.7.3/lib/.libs/fips.o \
/home/pi/gnutls-3.7.3/lib/.libs/safe-memfuncs.o \
/home/pi/gnutls-3.7.3/lib/.libs/profiles.o \
/home/pi/gnutls-3.7.3/lib/.libs/tls13-sig.o \
/home/pi/gnutls-3.7.3/lib/.libs/pk.o \
/home/pi/gnutls-3.7.3/lib/.libs/privkey_raw.o \
/home/pi/gnutls-3.7.3/lib/.libs/vko.o \
/home/pi/gnutls-3.7.3/lib/.libs/hello_ext_lib.o \
/home/pi/gnutls-3.7.3/lib/.libs/state.o \
/home/pi/gnutls-3.7.3/lib/.libs/pkcs11_int.o \
/home/pi/gnutls-3.7.3/lib/.libs/extv.o \
/home/pi/gnutls-3.7.3/lib/.libs/hello_ext.o \
/home/pi/gnutls-3.7.3/lib/.libs/tpm.o \
/home/pi/gnutls-3.7.3/lib/.libs/mbuffers.o \
/home/pi/gnutls-3.7.3/lib/.libs/global.o \
/home/pi/gnutls-3.7.3/lib/.libs/pkix_asn1_tab.o \
/home/pi/gnutls-3.7.3/lib/.libs/datum.o \
/home/pi/gnutls-3.7.3/lib/.libs/str-iconv.o \
/home/pi/gnutls-3.7.3/lib/.libs/verify-tofu.o \
/home/pi/gnutls-3.7.3/lib/.libs/auto-verify.o \
/home/pi/gnutls-3.7.3/lib/.libs/record.o \
/home/pi/gnutls-3.7.3/lib/.libs/str-idna.o \
/home/pi/gnutls-3.7.3/lib/.libs/pubkey.o \
/home/pi/gnutls-3.7.3/lib/.libs/dtls-sw.o \
/home/pi/gnutls-3.7.3/lib/.libs/ocsp-api.o \
/home/pi/gnutls-3.7.3/lib/.libs/prf.o \
/home/pi/gnutls-3.7.3/lib/.libs/x509_b64.o \
/home/pi/gnutls-3.7.3/lib/.libs/atfork.o \
/home/pi/gnutls-3.7.3/lib/.libs/priority.o \
/home/pi/gnutls-3.7.3/lib/.libs/mem.o \
/home/pi/gnutls-3.7.3/lib/.libs/buffers.o \
/home/pi/gnutls-3.7.3/lib/.libs/pkcs11_write.o \
/home/pi/gnutls-3.7.3/lib/.libs/cipher_int.o \
/home/pi/gnutls-3.7.3/lib/.libs/locks.o \
/home/pi/gnutls-3.7.3/lib/.libs/crypto-selftests.o \
/home/pi/gnutls-3.7.3/lib/.libs/cert-session.o \
/home/pi/gnutls-3.7.3/lib/.libs/cert-cred.o \
/home/pi/gnutls-3.7.3/lib/.libs/fingerprint.o \
/home/pi/gnutls-3.7.3/lib/.libs/file.o \
/home/pi/gnutls-3.7.3/lib/.libs/cipher.o \
/home/pi/gnutls-3.7.3/lib/.libs/randomart.o \
/home/pi/gnutls-3.7.3/lib/.libs/db.o \
/home/pi/gnutls-3.7.3/lib/.libs/dh.o \
/home/pi/gnutls-3.7.3/lib/.libs/ecc.o \
/home/pi/gnutls-3.7.3/lib/.libs/system.o \
/home/pi/gnutls-3.7.3/lib/.libs/str.o \
/home/pi/gnutls-3.7.3/lib/.libs/iov.o \
/home/pi/gnutls-3.7.3/lib/.libs/pkcs11x.o \
/home/pi/gnutls-3.7.3/lib/.libs/dtls.o \
/home/pi/gnutls-3.7.3/lib/.libs/handshake-tls13.o \
/home/pi/gnutls-3.7.3/lib/.libs/dh-session.o \
/home/pi/gnutls-3.7.3/lib/.libs/system_override.o \
/home/pi/gnutls-3.7.3/lib/.libs/privkey.o \
/home/pi/gnutls-3.7.3/lib/.libs/mpi.o \
/home/pi/gnutls-3.7.3/lib/.libs/tls-sig.o \
/home/pi/gnutls-3.7.3/lib/.libs/kx.o \
/home/pi/gnutls-3.7.3/lib/.libs/constate.o \
/home/pi/gnutls-3.7.3/lib/.libs/stek.o \
/home/pi/gnutls-3.7.3/lib/.libs/errors.o \
/home/pi/gnutls-3.7.3/lib/.libs/handshake.o \
/home/pi/gnutls-3.7.3/lib/.libs/crypto-selftests-pk.o \
/home/pi/gnutls-3.7.3/lib/.libs/auth.o \
/home/pi/gnutls-3.7.3/lib/.libs/anon_cred.o \
/home/pi/gnutls-3.7.3/lib/.libs/cipher-cbc.o \
/home/pi/gnutls-3.7.3/lib/.libs/cert-cred-x509.o \
/home/pi/gnutls-3.7.3/lib/.libs/sslv2_compat.o \
/home/pi/gnutls-3.7.3/lib/.libs/handshake-checks.o \
/home/pi/gnutls-3.7.3/lib/.libs/srp.o \
/home/pi/gnutls-3.7.3/lib/.libs/openpgp_compat.o \
/home/pi/gnutls-3.7.3/lib/.libs/debug.o \
/home/pi/gnutls-3.7.3/lib/.libs/crypto-api.o \
/home/pi/gnutls-3.7.3/lib/.libs/psk.o \
/home/pi/gnutls-3.7.3/lib/.libs/urls.o \
/home/pi/gnutls-3.7.3/lib/.libs/secrets.o \
/home/pi/gnutls-3.7.3/lib/.libs/random.o \
/home/pi/gnutls-3.7.3/lib/.libs/supplemental.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/early_data.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/certificate_request.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/certificate_verify.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/encrypted_extensions.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/anti_replay.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/key_update.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/post_handshake.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/session_ticket.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/psk_ext_parser.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/certificate.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/finished.o \
/home/pi/gnutls-3.7.3/lib/tls13/.libs/hello_retry.o \
/home/pi/gnutls-3.7.3/lib/system/.libs/keys-dummy.o \
/home/pi/gnutls-3.7.3/lib/system/.libs/fastopen.o \
/home/pi/gnutls-3.7.3/lib/system/.libs/sockets.o \
/home/pi/gnutls-3.7.3/lib/system/.libs/threads.o \
/home/pi/gnutls-3.7.3/lib/system/.libs/ktls.o \
/home/pi/gnutls-3.7.3/lib/system/.libs/certs.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/srtp.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/supported_groups.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/server_cert_type.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/early_data.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/psk_ke_modes.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/heartbeat.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/max_record.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/ext_master_secret.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/record_size_limit.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/post_handshake.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/ec_point_formats.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/server_name.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/safe_renegotiation.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/pre_shared_key.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/etm.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/session_ticket.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/supported_versions.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/alpn.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/key_share.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/client_cert_type.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/status_request.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/cookie.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/srp.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/dumbfw.o \
/home/pi/gnutls-3.7.3/lib/ext/.libs/signature.o \
/home/pi/gnutls-3.7.3/lib/extras/.libs/randomart.o \
/home/pi/gnutls-3.7.3/lib/extras/.libs/hex.o \
/home/pi/gnutls-3.7.3/lib/accelerated/.libs/cryptodev-gcm.o \
/home/pi/gnutls-3.7.3/lib/accelerated/.libs/accelerated.o \
/home/pi/gnutls-3.7.3/lib/accelerated/.libs/cryptodev.o \
/home/pi/gnutls-3.7.3/lib/accelerated/.libs/afalg.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/verify.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/pkcs7-output.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/x509_dn.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/pkcs12_encr.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/tls_features.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/x509.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/sign.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/verify-high.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/virt-san.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/verify-high2.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/pkcs12_bag.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/x509_write.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/prov-seed.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/pkcs7-crypt.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/pkcs12.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/common.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/ip.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/extensions.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/time.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/spki.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/privkey_pkcs8_pbes1.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/dn.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/attributes.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/ocsp_output.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/x509_ext.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/email-verify.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/output.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/ocsp.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/name_constraints.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/privkey_pkcs8.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/pkcs7.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/privkey_openssl.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/privkey.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/mpi.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/key_decode.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/crl_write.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/crq.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/pkcs7-attrs.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/key_encode.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/krb5.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/hostname-verify.o \
/home/pi/gnutls-3.7.3/lib/x509/.libs/crl.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/cert.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/rsa.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/vko_gost.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/psk_passwd.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/srp_sb64.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/ecdhe.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/srp_passwd.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/rsa_psk.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/dh_common.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/srp_kx.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/dhe.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/dhe_psk.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/anon_ecdh.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/anon.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/srp_rsa.o \
/home/pi/gnutls-3.7.3/lib/auth/.libs/psk.o \
/home/pi/gnutls-3.7.3/src/udp-serv.o \
/home/pi/gnutls-3.7.3/src/benchmark.o \
/home/pi/gnutls-3.7.3/src/systemkey.o \
/home/pi/gnutls-3.7.3/src/dumpcfg-cfg.o \
/home/pi/gnutls-3.7.3/src/serv.o \
/home/pi/gnutls-3.7.3/src/p11tool-common.o \
/home/pi/gnutls-3.7.3/src/p11tool-certtool-common.o \
/home/pi/gnutls-3.7.3/src/p11tool-certtool-extras.o \
/home/pi/gnutls-3.7.3/src/tests.o \
/home/pi/gnutls-3.7.3/src/.libs/systemkey-tool-options.o \
/home/pi/gnutls-3.7.3/src/.libs/p11tool-options.o \
/home/pi/gnutls-3.7.3/src/.libs/gnutls-cli-debug-options.o \
/home/pi/gnutls-3.7.3/src/.libs/psktool-options.o \
/home/pi/gnutls-3.7.3/src/.libs/ocsptool-options.o \
/home/pi/gnutls-3.7.3/src/.libs/danetool-options.o \
/home/pi/gnutls-3.7.3/src/.libs/gnutls-serv-options.o \
/home/pi/gnutls-3.7.3/src/.libs/srptool-options.o \
/home/pi/gnutls-3.7.3/src/.libs/gnutls-cli-options.o \
/home/pi/gnutls-3.7.3/src/.libs/certtool-options.o \
/home/pi/gnutls-3.7.3/src/.libs/cfg.o \
/home/pi/gnutls-3.7.3/src/.libs/certtool-cfg.o \
/home/pi/gnutls-3.7.3/src/benchmark-cipher.o \
/home/pi/gnutls-3.7.3/src/certtool-extras.o \
/home/pi/gnutls-3.7.3/src/ocsptool-common.o \
/home/pi/gnutls-3.7.3/src/certtool-common.o \
/home/pi/gnutls-3.7.3/src/common.o \
/home/pi/gnutls-3.7.3/src/benchmark-tls.o \
/home/pi/gnutls-3.7.3/src/ocsptool.o \
/home/pi/gnutls-3.7.3/src/certtool.o \
/home/pi/gnutls-3.7.3/src/cli-debug.o \
/home/pi/gnutls-3.7.3/src/p11tool-p11tool.o \
/home/pi/gnutls-3.7.3/src/socket.o \
/home/pi/gnutls-3.7.3/src/psk.o \
/home/pi/gnutls-3.7.3/src/p11tool-pkcs11.o \
/home/pi/gnutls-3.7.3/src/srptool.o \
/home/pi/gnutls-3.7.3/src/cli.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/printf-parse.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/timespec.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/nstrftime.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/malloca.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/asnprintf.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/gl_linked_list.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/c-strcasecmp.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/gettime.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/cloexec.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/basename-lgpl.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/fd-hook.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/progname.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/hash-pjw-bare.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/xalloc-die.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/c-ctype.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/stat-time.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/sockets.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/read-file.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/parse-datetime.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/unistd.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/close-stream.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/mktime.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/xmalloc.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/fcntl.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/xsize.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/gl_xlist.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/free.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/time_rz.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/gl_list.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/exitfail.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/getprogname.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/printf-args.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/c-strncasecmp.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/bitrotate.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/vasnprintf.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/sys_socket.o \
/home/pi/gnutls-3.7.3/src/gl/.libs/hash.o \
/home/pi/gnutls-3.7.3/src/gl/glthread/.libs/threadlib.o \
/home/pi/gnutls-3.7.3/src/gl/glthread/.libs/lock.o \
/home/pi/gnutls-3.7.3/gl/.libs/printf-parse.o \
/home/pi/gnutls-3.7.3/gl/.libs/malloca.o \
/home/pi/gnutls-3.7.3/gl/.libs/asnprintf.o \
/home/pi/gnutls-3.7.3/gl/.libs/c-strcasecmp.o \
/home/pi/gnutls-3.7.3/gl/.libs/cloexec.o \
/home/pi/gnutls-3.7.3/gl/.libs/fd-hook.o \
/home/pi/gnutls-3.7.3/gl/.libs/hash-pjw-bare.o \
/home/pi/gnutls-3.7.3/gl/.libs/c-ctype.o \
/home/pi/gnutls-3.7.3/gl/.libs/stat-time.o \
/home/pi/gnutls-3.7.3/gl/.libs/read-file.o \
/home/pi/gnutls-3.7.3/gl/.libs/unistd.o \
/home/pi/gnutls-3.7.3/gl/.libs/fcntl.o \
/home/pi/gnutls-3.7.3/gl/.libs/xsize.o \
/home/pi/gnutls-3.7.3/gl/.libs/free.o \
/home/pi/gnutls-3.7.3/gl/.libs/printf-args.o \
/home/pi/gnutls-3.7.3/gl/.libs/c-strncasecmp.o \
/home/pi/gnutls-3.7.3/gl/.libs/bitrotate.o \
/home/pi/gnutls-3.7.3/gl/.libs/vasnprintf.o \
/home/pi/gnutls-3.7.3/gl/.libs/sys_socket.o \
/home/pi/gnutls-3.7.3/gl/.libs/hash.o \
/home/pi/gnutls-3.7.3/gl/glthread/.libs/threadlib.o \
/home/pi/gnutls-3.7.3/gl/glthread/.libs/lock.o