ar rcs libcamera.a \
src-libcamera/build/utils/ipu3/ipu3-unpack.p/ipu3-unpack.c.o \
src-libcamera/build/src/ipa/rkisp1/ipa_rkisp1.so.p/rkisp1.cpp.o \
src-libcamera/build/src/ipa/rkisp1/ipa_rkisp1.so.p/ipa_context.cpp.o \
src-libcamera/build/src/ipa/rkisp1/ipa_rkisp1.so.p/algorithms_agc.cpp.o \
src-libcamera/build/src/ipa/ipu3/ipa_ipu3.so.p/ipa_context.cpp.o \
src-libcamera/build/src/ipa/ipu3/ipa_ipu3.so.p/algorithms_awb.cpp.o \
src-libcamera/build/src/ipa/ipu3/ipa_ipu3.so.p/ipu3.cpp.o \
src-libcamera/build/src/ipa/ipu3/ipa_ipu3.so.p/algorithms_agc.cpp.o \
src-libcamera/build/src/ipa/ipu3/ipa_ipu3.so.p/algorithms_blc.cpp.o \
src-libcamera/build/src/ipa/ipu3/ipa_ipu3.so.p/algorithms_tone_mapping.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_dpc.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_sdn.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_lux.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/cam_helper_imx219.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_geq.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/cam_helper_imx519.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/cam_helper_imx477.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_black_level.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/cam_helper_ov9281.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/cam_helper_imx290.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_focus.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/cam_helper.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_algorithm.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_sharpen.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_alsc.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/md_parser_smia.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_pwl.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_ccm.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/raspberrypi.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_agc.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_noise.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_contrast.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_rpi_awb.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/cam_helper_ov5647.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_device_status.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_controller.cpp.o \
src-libcamera/build/src/ipa/raspberrypi/ipa_rpi.so.p/controller_histogram.cpp.o \
src-libcamera/build/src/ipa/vimc/ipa_vimc.so.p/vimc.cpp.o \
src-libcamera/build/src/ipa/libipa/libipa.a.p/histogram.cpp.o \
src-libcamera/build/src/ipa/libipa/libipa.a.p/camera_sensor_helper.cpp.o \
src-libcamera/build/src/ipa/libipa/libipa.a.p/libipa.cpp.o \
src-libcamera/build/src/cam/cam.p/file_sink.cpp.o \
src-libcamera/build/src/cam/cam.p/stream_options.cpp.o \
src-libcamera/build/src/cam/cam.p/options.cpp.o \
src-libcamera/build/src/cam/cam.p/main.cpp.o \
src-libcamera/build/src/cam/cam.p/image.cpp.o \
src-libcamera/build/src/cam/cam.p/frame_sink.cpp.o \
src-libcamera/build/src/cam/cam.p/camera_session.cpp.o \
src-libcamera/build/src/cam/cam.p/event_loop.cpp.o \
src-libcamera/build/src/lc-compliance/lc-compliance.p/capture_test.cpp.o \
src-libcamera/build/src/lc-compliance/lc-compliance.p/main.cpp.o \
src-libcamera/build/src/lc-compliance/lc-compliance.p/.._.._subprojects_googletest-release-1.11.0_googletest_src_gtest-all.cc.o \
src-libcamera/build/src/lc-compliance/lc-compliance.p/.._cam_options.cpp.o \
src-libcamera/build/src/lc-compliance/lc-compliance.p/simple_capture.cpp.o \
src-libcamera/build/src/lc-compliance/lc-compliance.p/environment.cpp.o \
src-libcamera/build/src/lc-compliance/lc-compliance.p/.._cam_event_loop.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_rkisp1_rkisp1_path.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/framebuffer_allocator.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/media_object.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_raspberrypi_dma_heaps.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/controls.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_ipu3_cio2.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/device_enumerator_sysfs.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipa_interface.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_simple_converter.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/v4l2_subdevice.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/sysfs.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/v4l2_videodevice.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipc_pipe_unixsocket.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipa_manager.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_ipu3_ipu3.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/meson-generated_.._ipa_pub_key.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/camera.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipc_pipe.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/request.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/byte_stream_buffer.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/device_enumerator.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_raspberrypi_raspberrypi.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/camera_sensor_properties.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/fence.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_vimc_vimc.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_handler.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/camera_lens.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/source_paths.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/meson-generated_.._proxy_raspberrypi_ipa_proxy.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/delayed_controls.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/camera_manager.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/mapped_framebuffer.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/v4l2_device.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/meson-generated_.._proxy_ipu3_ipa_proxy.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/control_serializer.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pixel_format.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/color_space.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_rkisp1_rkisp1.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/geometry.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/framebuffer.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/transform.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_ipu3_imgu.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/meson-generated_.._version.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/v4l2_pixelformat.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/camera_sensor.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/camera_controls.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pub_key.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipa_module.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/bayer_format.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/meson-generated_.._proxy_rkisp1_ipa_proxy.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipa_data_serializer.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/formats.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/media_device.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/stream.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_ipu3_frames.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/meson-generated_.._control_ids.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_raspberrypi_rpi_stream.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_uvcvideo_uvcvideo.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/process.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/meson-generated_.._property_ids.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/pipeline_simple_simple.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/meson-generated_.._proxy_vimc_ipa_proxy.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipc_unixsocket.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipa_proxy.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/control_validator.cpp.o \
src-libcamera/build/src/libcamera/libcamera.so.0.0.0.p/ipa_controls.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/event_notifier.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/utils.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/bound_method.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/backtrace.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/flags.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/event_dispatcher.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/file.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/mutex.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/event_dispatcher_poll.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/signal.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/thread.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/semaphore.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/message.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/shared_fd.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/timer.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/class.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/log.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/object.cpp.o \
src-libcamera/build/src/libcamera/base/libcamera-base.so.0.0.0.p/unique_fd.cpp.o \
src-libcamera/build/src/libcamera/proxy/worker/raspberrypi_ipa_proxy.p/meson-generated_.._raspberrypi_ipa_proxy_worker.cpp.o \
src-libcamera/build/src/libcamera/proxy/worker/vimc_ipa_proxy.p/meson-generated_.._vimc_ipa_proxy_worker.cpp.o \
src-libcamera/build/src/libcamera/proxy/worker/ipu3_ipa_proxy.p/meson-generated_.._ipu3_ipa_proxy_worker.cpp.o \
src-libcamera/build/src/libcamera/proxy/worker/rkisp1_ipa_proxy.p/meson-generated_.._rkisp1_ipa_proxy_worker.cpp.o \
src-libcamera/build/test/signal.p/signal.cpp.o \
src-libcamera/build/test/hotplug-cameras.p/hotplug-cameras.cpp.o \
src-libcamera/build/test/message.p/message.cpp.o \
src-libcamera/build/test/timer.p/timer.cpp.o \
src-libcamera/build/test/flags.p/flags.cpp.o \
src-libcamera/build/test/event-thread.p/event-thread.cpp.o \
src-libcamera/build/test/bayer-format.p/bayer-format.cpp.o \
src-libcamera/build/test/object-delete.p/object-delete.cpp.o \
src-libcamera/build/test/public-api.p/public-api.cpp.o \
src-libcamera/build/test/shared-fd.p/shared-fd.cpp.o \
src-libcamera/build/test/fence.p/fence.cpp.o \
src-libcamera/build/test/ipc/unixsocket.p/unixsocket.cpp.o \
src-libcamera/build/test/ipc/unixsocket_ipc.p/unixsocket_ipc.cpp.o \
src-libcamera/build/test/v4l2_videodevice/formats.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/formats.p/formats.cpp.o \
src-libcamera/build/test/v4l2_videodevice/capture_async.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/capture_async.p/capture_async.cpp.o \
src-libcamera/build/test/v4l2_videodevice/buffer_sharing.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/buffer_sharing.p/buffer_sharing.cpp.o \
src-libcamera/build/test/v4l2_videodevice/stream_on_off.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/stream_on_off.p/stream_on_off.cpp.o \
src-libcamera/build/test/v4l2_videodevice/double_open.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/double_open.p/double_open.cpp.o \
src-libcamera/build/test/v4l2_videodevice/v4l2_m2mdevice.p/v4l2_m2mdevice.cpp.o \
src-libcamera/build/test/v4l2_videodevice/v4l2_m2mdevice.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/buffer_cache.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/buffer_cache.p/buffer_cache.cpp.o \
src-libcamera/build/test/v4l2_videodevice/controls.p/controls.cpp.o \
src-libcamera/build/test/v4l2_videodevice/controls.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/request_buffers.p/v4l2_videodevice_test.cpp.o \
src-libcamera/build/test/v4l2_videodevice/request_buffers.p/request_buffers.cpp.o \
src-libcamera/build/test/camera-sensor.p/camera-sensor.cpp.o \
src-libcamera/build/test/media_device/media_device_link_test.p/media_device_link_test.cpp.o \
src-libcamera/build/test/media_device/media_device_acquire.p/media_device_acquire.cpp.o \
src-libcamera/build/test/media_device/media_device_print_test.p/media_device_print_test.cpp.o \
src-libcamera/build/test/media_device/liblib_mdev_test.a.p/media_device_test.cpp.o \
src-libcamera/build/test/controls/control_info.p/control_info.cpp.o \
src-libcamera/build/test/controls/control_info_map.p/control_info_map.cpp.o \
src-libcamera/build/test/controls/control_list.p/control_list.cpp.o \
src-libcamera/build/test/controls/control_value.p/control_value.cpp.o \
src-libcamera/build/test/camera/configuration_default.p/configuration_default.cpp.o \
src-libcamera/build/test/camera/buffer_import.p/buffer_import.cpp.o \
src-libcamera/build/test/camera/statemachine.p/statemachine.cpp.o \
src-libcamera/build/test/camera/camera_reconfigure.p/camera_reconfigure.cpp.o \
src-libcamera/build/test/camera/capture.p/capture.cpp.o \
src-libcamera/build/test/camera/configuration_set.p/configuration_set.cpp.o \
src-libcamera/build/test/delayed_controls.p/delayed_controls.cpp.o \
src-libcamera/build/test/stream/stream_formats.p/stream_formats.cpp.o \
src-libcamera/build/test/object.p/object.cpp.o \
src-libcamera/build/test/libtest/liblibtest.a.p/camera_test.cpp.o \
src-libcamera/build/test/libtest/liblibtest.a.p/test.cpp.o \
src-libcamera/build/test/libtest/liblibtest.a.p/buffer_source.cpp.o \
src-libcamera/build/test/threads.p/threads.cpp.o \
src-libcamera/build/test/unique-fd.p/unique-fd.cpp.o \
src-libcamera/build/test/timer-thread.p/timer-thread.cpp.o \
src-libcamera/build/test/object-invoke.p/object-invoke.cpp.o \
src-libcamera/build/test/process/process_test.p/process_test.cpp.o \
src-libcamera/build/test/file.p/file.cpp.o \
src-libcamera/build/test/event-dispatcher.p/event-dispatcher.cpp.o \
src-libcamera/build/test/byte-stream-buffer.p/byte-stream-buffer.cpp.o \
src-libcamera/build/test/serialization/generated_serializer/generated_serializer_test.p/generated_serializer_test.cpp.o \
src-libcamera/build/test/serialization/ipa_data_serializer_test.p/ipa_data_serializer_test.cpp.o \
src-libcamera/build/test/serialization/ipa_data_serializer_test.p/serialization_test.cpp.o \
src-libcamera/build/test/serialization/control_serialization.p/control_serialization.cpp.o \
src-libcamera/build/test/serialization/control_serialization.p/serialization_test.cpp.o \
src-libcamera/build/test/ipa/ipa_interface_test.p/ipa_interface_test.cpp.o \
src-libcamera/build/test/ipa/ipa_module_test.p/ipa_module_test.cpp.o \
src-libcamera/build/test/geometry.p/geometry.cpp.o \
src-libcamera/build/test/log/log_process.p/log_process.cpp.o \
src-libcamera/build/test/log/log_api.p/log_api.cpp.o \
src-libcamera/build/test/pipeline/rkisp1/rkisp1_pipeline_test.p/rkisp1_pipeline_test.cpp.o \
src-libcamera/build/test/pipeline/ipu3/ipu3_pipeline_test.p/ipu3_pipeline_test.cpp.o \
src-libcamera/build/test/pixel-format.p/pixel-format.cpp.o \
src-libcamera/build/test/mapped-buffer.p/mapped-buffer.cpp.o \
src-libcamera/build/test/signal-threads.p/signal-threads.cpp.o \
src-libcamera/build/test/v4l2_subdevice/test_formats.p/v4l2_subdevice_test.cpp.o \
src-libcamera/build/test/v4l2_subdevice/test_formats.p/test_formats.cpp.o \
src-libcamera/build/test/v4l2_subdevice/list_formats.p/v4l2_subdevice_test.cpp.o \
src-libcamera/build/test/v4l2_subdevice/list_formats.p/list_formats.cpp.o \
src-libcamera/build/test/span.p/span.cpp.o \
src-libcamera/build/test/utils.p/utils.cpp.o \
src-libcamera/build/test/event.p/event.cpp.o